### ISSUE TITLE
What filetype if nui windows?

### ISSUE THREAD

**Issue by RAprogramm** [MunifTanjim/nui.nvim#244] opened 2023-03-17 07:49 UTC
### Discussed in https://github.com/MunifTanjim/nui.nvim/discussions/243

<div type='discussions-op-text'>

<sup>Originally posted by **RAprogramm** March 17, 2023</sup>
 
[Screencast_00003.webm](https://user-images.githubusercontent.com/70325462/225843962-afec2a18-2dfb-4901-aa71-26323bbd3340.webm)

when opening any nui window - lualine looks like no good (tell that is not git repository but it is). to disable it i need to know filetype or buf type of nui. but i can't get it.
help me please</div>
`buf_options = { filetype = 'prompt' }` - this will decide my problem, BUT where i can paste it?
somewere in init options?

**Comment by MunifTanjim** [comment] 2023-03-17 07:53
Duplicate of https://github.com/MunifTanjim/nui.nvim/discussions/243

**Closed by MunifTanjim** 2023-03-17 07:53 UTC
Labels: discussion: question
