### ISSUE TITLE
`nvim_win_set_config()` can be called on invalid window id

### ISSUE THREAD

**Issue by przepompownia** [MunifTanjim/nui.nvim#211] opened 2022-11-14 12:06 UTC
![image](https://user-images.githubusercontent.com/11404453/201651308-60f48c67-aae9-42ae-9387-60703718a3e1.png)
![image](https://user-images.githubusercontent.com/11404453/201652084-a34c3cec-3289-46b8-a56d-5acbe859ef16.png)

Hello,

I get the above errors testing noice.nvim on Goneovim (see https://github.com/folke/noice.nvim/discussions/212) where cmdline popup still cannot be shown. 

On my local copy I added two conditions
```diff
diff --git a/lua/nui/popup/border.lua b/lua/nui/popup/border.lua
index 0160a49..a309488 100644
--- a/lua/nui/popup/border.lua
+++ b/lua/nui/popup/border.lua
@@ -537,7 +537,7 @@ function Border:_relayout()
 
   internal.lines = calculate_buf_lines(internal)
 
-  if self.winid then
+  if self.winid and vim.api.nvim_win_is_valid(self.winid) then
     vim.api.nvim_win_set_config(self.winid, self.win_config)
   end
 
diff --git a/lua/nui/popup/init.lua b/lua/nui/popup/init.lua
index fe838c7..922e14a 100644
--- a/lua/nui/popup/init.lua
+++ b/lua/nui/popup/init.lua
@@ -360,7 +360,7 @@ function Popup:update_layout(config)
 
   self._.layout_ready = true
 
-  if self.winid then
+  if self.winid and vim.api.nvim_win_is_valid(self.winid) then
     vim.api.nvim_win_set_config(self.winid, self.win_config)
   end
 end
```
but I assume you know better solution than only checking.

**Comment by MunifTanjim** [comment] 2022-11-14 12:29
Looks like somebody is closing the window, leaving the `self.winid` behind. That shouldn't happen to begin with. Adding that `nvim_win_is_valid` check is probably just hiding the symptom, not solving the actual issue.

So question is - who's killing the window?

**Comment by folke** [comment] 2022-11-15 13:51
Yeah, Noice definitely has issues in guis. The gui needs to work correctly when multiple external uis are attached. I assume Goneovim and others expect to be the only one that is connected.

**Comment by MunifTanjim** [comment] 2022-11-15 14:53
Closing this issue, since it's actually caused by Goneovim.

**Closed by MunifTanjim** 2022-11-15 14:53 UTC
Labels: invalid
