### ISSUE TITLE
Add NuiTree:get_expanded_nodes() and set_expanded_nodes()

### ISSUE THREAD

**Issue by cseickel** [MunifTanjim/nui.nvim#73] opened 2021-12-20 01:23 UTC
The problem I am trying to solve is that I want to keep the state of what nodes are expanded when refreshing the tree with a set_nodes call, or navigating up when browsing the file system.

The method that I've seen from other tree controls, which I think is a good idea, is to have methods to export that state and re-import it later. It could also be useful for other tree structures where you just want to set certain nodes to open by default. I think using a list of node ids for this is sufficient.

**Comment by MunifTanjim** [comment] 2021-12-20 06:04
Hmm, that's a perfectly valid use-case 🤔

Instead of adding `get_expanded_nodes` and `set_expanded_nodes` methods, how about adding `tree:get_nodes(parent_id?)` method?

That way it's more generalized and you create various functions on top of it, e.g.:

```lua
local function get_expanded_nodes(tree)
  local nodes = {}

  local function process(node)
    if node:is_expanded() then
      table.insert(nodes, node)

      if node:has_children() then
        for _, node in tree:get_nodes(node:get_id()) do
          process(node)
        end
      end
    end
  end

  for _, node in tree:get_nodes() do
    process(node)
  end

  return nodes
end
```

We can also provide this `get_expanded_nodes` function in `require("nui.tree.util")` along with other often-used helper utilities so that people don't need to reimplement them.

What do you think?

**Comment by cseickel** [comment] 2021-12-20 12:40
In that scenario, the usage would be like this?
```
local tree_util = require("nui.tree.util")

local expanded_ids = tree_util.get_expanded_nodes(tree)
...
tree_util.set_expanded_nodes(tree, expanded_ids)
```

That's OK, and it's way better than having to implement it myself, but it's a little confusing. As the utils grows, we'll have some methods for working with a tree as methods on the tree object itself and some as static functions. How do I know which to use for each method? It's much easier to use a library that is consistent. Either all methods, all functions, or all in both and pick your style.

My vote would be to do as you suggest, but add NuiTree instance methods as the public interface.

If you just think this would be a less used function, you could also segment the documentation into "common" or "core" methods and "utilities" or "extras."

**Comment by MunifTanjim** [comment] 2021-12-20 14:22
My intention with `NuiTree` was to provide what is absolutely necessary for the user to implement whatever they want.

So I'm kinda hesitant about adding those functions as `tree:*` methods. That's why I suggested the `require("nui.tree.util")` idea.

If we just add the `tree:get_nodes` method, I think that would complete the feature-set of `NuiTree`. And with the existing methods, you can implement anything you want, however complex they might be.

---

Think of a case like this,

- Say `nui.nvim` provides the `tree:{get,set}_expanded_nodes` methods
- You're maintaining a tree explorer plugin and implemented the ui using `nui.nvim`
- Your plugin uses `tree:{get,set}_expanded_nodes` methods to save and restore the expanded state

Now what happens you need to implement a feature where you need to expand only the first 2 level of depth? The built-in `tree:{get,set}_expanded_nodes` methods would be kinda use-less in that case. So you'll need to:
- either implement those two functions yourself
- or those built-in methods in `nui.nvim` need to accept additional params to support that

See where the problem is? If you go with the first option, then adding those methods to `NuiTree` was pointless. If you go with the second option, `NuiTree` simply can't keep up with add the possible use-cases and keep adding additional things.

I hope this makes sense... 😄

**Comment by cseickel** [comment] 2021-12-20 15:25
I can certainly appreciate that you want to keep the feature set simple and maintainable. A public `tree:get_nodes` method would certainly be sufficient to implement the functionality on my own.

Thanks!

**Comment by MunifTanjim** [comment] 2021-12-20 17:42
Closing since `{get,set}_expanded_nodes` can now be implemented using `tree:get_nodes` method.

Also added the `get_expanded_nodes` snippet in https://github.com/MunifTanjim/nui.nvim/wiki/nui.tree

**Closed by MunifTanjim** 2021-12-20 17:42 UTC
Labels: tag: enhancement
