### ISSUE TITLE
Inputs broken by commit which sets noautocmd

### ISSUE THREAD

**Issue by beauwilliams** [MunifTanjim/nui.nvim#209] opened 2022-11-04 00:49 UTC
This commit https://github.com/MunifTanjim/nui.nvim/commit/4715f6092443f0b8fb9a3bcb0cfd03202bb03477

Led to a bug on my machine where inputs no longer work with my autocommands which worked previously.

It is a conflict with my plugin https://github.com/beauwilliams/focus.nvim

Here is what the input used to look like
<img width="461" alt="Screen Shot 2022-11-04 at 11 46 50 am" src="https://user-images.githubusercontent.com/7098556/199861602-925abdd6-be75-4fc5-ad51-464921ff1d92.png">

Here is what it looks like now
<img width="600" alt="Screen Shot 2022-11-04 at 11 47 25 am" src="https://user-images.githubusercontent.com/7098556/199861491-d75770a2-523a-4b3e-ae18-cd048a111d34.png">

I'm going to lock this package for now on the commit before the breaking change. Perhaps we can look into how this should be fixed to ensure compatibility, be it on my end or nui

**Comment by MunifTanjim** [comment] 2022-11-04 05:32
Can you give me a reproducible example?

**Comment by beauwilliams** [comment] 2022-11-04 05:51
Absolutely, here is the code I am using to create and manage the Input instance 

https://github.com/beauwilliams/Dotfiles/blob/master/Vim/nvim/lua/plugins/_my_terminal.lua

I can solve the issue by disabling `focus.nvim` plugin, or by checking out to before the commit mentioned above.

I'll have do dig into the importantce of noautocmd and why it was added. It's really a tight rope walk with nvim at the moment because window management is a mishmash of autocmds relying on filetypes/buftypes which are themselves set with autocmds at the moment essentially 😅

**Comment by MunifTanjim** [comment] 2022-11-04 06:42
I ran it with a clean setup with `focus.nvim` and `nui.nvim` installed. And then ran `:MyTermRunTaskCommand` from neovim. Couldn't reproduce it.

It would be really helpful if you could share a minimal reproducible example.

**Comment by beauwilliams** [comment] 2022-11-04 11:23
Interesting, it must be something else then, let me try to make a reproducible example

**Comment by MunifTanjim** [comment] 2023-02-03 17:33
Closing since this is not reproducible.

**Closed by MunifTanjim** 2023-02-03 17:33 UTC
